name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      yarn-cache-dir-path: ${{ steps.yarn-cache-dir-path.outputs.out }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: ./.github/local-actions/yarn-install-and-cache

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: ./.github/local-actions/yarn-install-and-cache
      - name: Run linter
        run: |
          yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: ./.github/local-actions/yarn-install-and-cache
      - name: Run tests
        run: |
          yarn test:ci

  build:
    name: Build
    needs:
      - test
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: ./.github/local-actions/yarn-install-and-cache
      - name: Build
        run: |
          yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: ./dist

  deploy:
    name: Deploy
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-files
          path: ./dist
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
